import fs from 'fs';
import path from 'path';
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

export interface ExportedProject {
  folderPath: string;
  files: {
    [filepath: string]: string;
  };
}

/**
 * Generates the server.ts file
 */
function generateServerTs(tableNames: string[]): string {
  const imports = tableNames
    .map((name) => {
      const camelCase = name.charAt(0).toLowerCase() + name.slice(1);
      return `import ${camelCase}Routes from './routes/${camelCase}.routes';`;
    })
    .join('\n');

  const routeRegistrations = tableNames
    .map((name) => {
      const camelCase = name.charAt(0).toLowerCase() + name.slice(1);
      return `app.use('/api/${camelCase}', ${camelCase}Routes);`;
    })
    .join('\n');

  return `import express, { Express, Request, Response } from 'express';
import cors from 'cors';
import { PrismaClient } from '@prisma/client';

${imports}

const app: Express = express();
const port = process.env.PORT || 5000;
const prisma = new PrismaClient();

// Middleware
app.use(cors());
app.use(express.json());

// Routes
${routeRegistrations}

// Health check
app.get('/api/health', (req: Request, res: Response) => {
  res.json({ status: 'ok' });
});

// Start server
app.listen(port, () => {
  console.log(\`Server running at http://localhost:\${port}\`);
});

export default app;
`;
}

/**
 * Generates package.json
 */
function generatePackageJson(tableNames: string[]): string {
  return JSON.stringify(
    {
      name: 'visual-api-orchestrator-backend',
      version: '1.0.0',
      description: 'Auto-generated backend with CRUD API routes',
      main: 'server.ts',
      scripts: {
        dev: 'ts-node src/server.ts',
        build: 'tsc',
        start: 'node dist/server.js',
      },
      dependencies: {
        express: '^4.18.2',
        cors: '^2.8.5',
        '@prisma/client': '^5.0.0',
      },
      devDependencies: {
        typescript: '^5.0.0',
        'ts-node': '^10.9.1',
        '@types/express': '^4.17.17',
        '@types/node': '^20.3.1',
        prisma: '^5.0.0',
      },
    },
    null,
    2
  );
}

/**
 * Generates README.md with setup instructions
 */
function generateReadme(tableNames: string[]): string {
  const tablesList = tableNames
    .map((name) => {
      const camelCase = name.charAt(0).toLowerCase() + name.slice(1);
      return `- \`/api/${camelCase}\` - ${name} CRUD endpoints`;
    })
    .join('\n');

  return `# Visual API Orchestrator - Generated Backend

This is an auto-generated backend project with complete CRUD API routes for your database tables.

## Project Structure

\`\`\`
.
├── prisma/
│   ├── schema.prisma      # Prisma schema for all tables
│   └── dev.db             # SQLite database (auto-created)
├── src/
│   ├── server.ts          # Express server setup
│   ├── routes/            # CRUD route files
│   │   └── [table].routes.ts
│   └── types.ts           # TypeScript types
├── package.json           # Dependencies
├── tsconfig.json          # TypeScript config
└── README.md              # This file
\`\`\`

## Generated Tables

${tablesList}

## Quick Start

### 1. Install Dependencies

\`\`\`bash
npm install
\`\`\`

### 2. Setup Database

\`\`\`bash
npx prisma db push
\`\`\`

### 3. Start Development Server

\`\`\`bash
npm run dev
\`\`\`

The server will run on \`http://localhost:5000\`

## API Endpoints

Each table has the following CRUD endpoints:

\`\`\`
POST   /api/<table>        Create a new record
GET    /api/<table>        Get all records
GET    /api/<table>/:id    Get a single record by ID
PUT    /api/<table>/:id    Update a record
DELETE /api/<table>/:id    Delete a record
\`\`\`

## Example Usage

### Create a Record

\`\`\`bash
curl -X POST http://localhost:5000/api/products \\
  -H "Content-Type: application/json" \\
  -d '{ "name": "iPhone", "price": 999 }'
\`\`\`

### Get All Records

\`\`\`bash
curl http://localhost:5000/api/products
\`\`\`

### Get Single Record

\`\`\`bash
curl http://localhost:5000/api/products/123
\`\`\`

### Update a Record

\`\`\`bash
curl -X PUT http://localhost:5000/api/products/123 \\
  -H "Content-Type: application/json" \\
  -d '{ "price": 1099 }'
\`\`\`

### Delete a Record

\`\`\`bash
curl -X DELETE http://localhost:5000/api/products/123
\`\`\`

## View Database

To view and manage your database visually:

\`\`\`bash
npx prisma studio
\`\`\`

This opens the Prisma Studio at \`http://localhost:5555\`

## Environment Variables

Create a \`.env\` file in the root directory:

\`\`\`
DATABASE_URL="file:./prisma/dev.db"
PORT=5000
\`\`\`

## Deployment

To build for production:

\`\`\`bash
npm run build
npm start
\`\`\`

## Support

Generated by Visual API Orchestrator
Visit: https://your-domain.com

---

Happy coding! 🚀
`;
}

/**
 * Generates a CRUD route file for a table
 */
function generateRouteFile(tableName: string): string {
  const camelCaseName = tableName.charAt(0).toLowerCase() + tableName.slice(1);
  const PascalCaseName = tableName.charAt(0).toUpperCase() + tableName.slice(1);

  return `import express, { Router, Request, Response } from 'express';
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();
const router: Router = express.Router();

/**
 * POST /api/${camelCaseName}
 * Creates a new ${camelCaseName}
 */
router.post('/', async (req: Request, res: Response) => {
  try {
    const data = req.body;
    
    if (!data || typeof data !== 'object') {
      res.status(400).json({
        success: false,
        error: 'Request body must be a valid JSON object',
      });
      return;
    }

    const ${camelCaseName} = await prisma.${camelCaseName}.create({
      data,
    });
    
    res.status(201).json({
      success: true,
      data: ${camelCaseName},
    });
  } catch (error: any) {
    res.status(400).json({
      success: false,
      error: error.message || 'Failed to create ${camelCaseName}',
    });
  }
});

/**
 * GET /api/${camelCaseName}
 * Retrieves all ${camelCaseName} records
 */
router.get('/', async (req: Request, res: Response) => {
  try {
    const ${camelCaseName}s = await prisma.${camelCaseName}.findMany();
    
    res.json({
      success: true,
      data: ${camelCaseName}s,
    });
  } catch (error: any) {
    res.status(500).json({
      success: false,
      error: error.message || 'Failed to retrieve ${camelCaseName}s',
    });
  }
});

/**
 * GET /api/${camelCaseName}/:id
 * Retrieves a single ${camelCaseName} by ID
 */
router.get('/:id', async (req: Request, res: Response) => {
  try {
    const { id } = req.params;
    
    if (!id) {
      res.status(400).json({
        success: false,
        error: 'ID parameter is required',
      });
      return;
    }

    const ${camelCaseName} = await prisma.${camelCaseName}.findUnique({
      where: { id },
    });
    
    if (!${camelCaseName}) {
      res.status(404).json({
        success: false,
        error: '${PascalCaseName} not found',
      });
      return;
    }
    
    res.json({
      success: true,
      data: ${camelCaseName},
    });
  } catch (error: any) {
    res.status(500).json({
      success: false,
      error: error.message || 'Failed to retrieve ${camelCaseName}',
    });
  }
});

/**
 * PUT /api/${camelCaseName}/:id
 * Updates an existing ${camelCaseName}
 */
router.put('/:id', async (req: Request, res: Response) => {
  try {
    const { id } = req.params;
    const data = req.body;
    
    if (!id) {
      res.status(400).json({
        success: false,
        error: 'ID parameter is required',
      });
      return;
    }

    if (!data || typeof data !== 'object') {
      res.status(400).json({
        success: false,
        error: 'Request body must be a valid JSON object',
      });
      return;
    }

    const ${camelCaseName} = await prisma.${camelCaseName}.update({
      where: { id },
      data,
    });
    
    res.json({
      success: true,
      data: ${camelCaseName},
    });
  } catch (error: any) {
    res.status(400).json({
      success: false,
      error: error.message || 'Failed to update ${camelCaseName}',
    });
  }
});

/**
 * DELETE /api/${camelCaseName}/:id
 * Deletes a ${camelCaseName}
 */
router.delete('/:id', async (req: Request, res: Response) => {
  try {
    const { id } = req.params;
    
    if (!id) {
      res.status(400).json({
        success: false,
        error: 'ID parameter is required',
      });
      return;
    }

    const ${camelCaseName} = await prisma.${camelCaseName}.delete({
      where: { id },
    });
    
    res.json({
      success: true,
      data: ${camelCaseName},
    });
  } catch (error: any) {
    res.status(400).json({
      success: false,
      error: error.message || 'Failed to delete ${camelCaseName}',
    });
  }
});

export default router;
`;
}

/**
 * Generates a complete backend project for export
 */
export async function generateBackendProject(): Promise<ExportedProject> {
  try {
    // Step 1: Get all tables from the database
    const allTables = await prisma.table.findMany();
    const tableNames = allTables.map((t) => t.name);

    if (tableNames.length === 0) {
      throw new Error('No tables found. Please create at least one table before exporting.');
    }

    // Step 2: Read the current Prisma schema
    const schemaPath = path.join(process.cwd(), 'prisma', 'schema.prisma');
    const schemaContent = fs.readFileSync(schemaPath, 'utf-8');

    // Step 3: Generate all project files
    const files: ExportedProject['files'] = {
      'prisma/schema.prisma': schemaContent,
      'src/server.ts': generateServerTs(tableNames),
      'package.json': generatePackageJson(tableNames),
      'README.md': generateReadme(tableNames),
      '.env': 'DATABASE_URL="file:./prisma/dev.db"\nPORT=5000\n',
      'tsconfig.json': JSON.stringify(
        {
          compilerOptions: {
            target: 'ES2020',
            module: 'commonjs',
            lib: ['ES2020'],
            outDir: './dist',
            rootDir: './src',
            strict: true,
            esModuleInterop: true,
            skipLibCheck: true,
            forceConsistentCasingInFileNames: true,
            resolveJsonModule: true,
          },
          include: ['src'],
          exclude: ['node_modules', 'dist'],
        },
        null,
        2
      ),
    };

    // Step 4: Generate route files for each table
    tableNames.forEach((tableName) => {
      const camelCaseName = tableName.charAt(0).toLowerCase() + tableName.slice(1);
      const routeKey = `src/routes/${camelCaseName}.routes.ts`;
      files[routeKey] = generateRouteFile(tableName);
    });

    return {
      folderPath: path.join(process.cwd(), 'generated-backend'),
      files,
    };
  } catch (error: any) {
    throw new Error(`Failed to generate backend: ${error.message}`);
  }
}
